eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
server:
  port: 8088
spring:
  application:
    name: tree-config
    #配置git远程仓库地址
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiayuliao11/springconfig.git
          #配置 配置文件所在git远程库的文件夹名称
          search-paths: springcloud/**
          #如果项目是私有项目 需要配置git远程库用户名密码
          username: xiayuliao11
          password: li@112233

